import re, os

path = r'D:\下載\Mc-Plugin\src\main\java\com\customrpg\integration\npc\QuestBindGUI.java'

content = (
    'package com.customrpg.integration.npc;\n\n'
    'import fr.skytasul.quests.api.QuestsAPI;\n'
    'import fr.skytasul.quests.api.quests.Quest;\n'
    'import org.bukkit.Bukkit;\n'
    'import org.bukkit.Material;\n'
    'import org.bukkit.NamespacedKey;\n'
    'import org.bukkit.entity.Player;\n'
    'import org.bukkit.event.EventHandler;\n'
    'import org.bukkit.event.Listener;\n'
    'import org.bukkit.event.inventory.InventoryClickEvent;\n'
    'import org.bukkit.event.inventory.InventoryCloseEvent;\n'
    'import org.bukkit.inventory.Inventory;\n'
    'import org.bukkit.inventory.ItemStack;\n'
    'import org.bukkit.inventory.meta.ItemMeta;\n'
    'import org.bukkit.persistence.PersistentDataType;\n'
    'import org.bukkit.plugin.java.JavaPlugin;\n\n'
    'import java.util.*;\n\n'
    '/**\n'
    ' * QuestBindGUI \u2014 \u7ba1\u7406\u54e1\u9078\u64c7\u8981\u7d81\u5b9a\u5230 NPC \u7684\u4efb\u52d9\n'
    ' *\n'
    ' * \u958b\u555f\u65b9\u5f0f\uff1a\u5c0d NPC \u6309 Shift+\u53f3\u9375\uff08\u9700 customrpg.npc.admin \u6b0a\u9650\uff09\n'
    ' *          \u6216 /rpgnpc bind <npc_id>\n'
    ' *\n'
    ' * \u9078\u64c7\u4efb\u52d9\u5f8c\uff0c\u7cfb\u7d71\u5c07\u4efb\u52d9 ID \u5132\u5b58\u5230 npcs.yml\u3002\n'
    ' * \u4e4b\u5f8c\u73a9\u5bb6\u5c0d\u6b64 NPC \u53f3\u9375\uff0c\u76f4\u63a5\u89f8\u767c quest.doNpcClick(player)\u3002\n'
    ' */\n'
    'public class QuestBindGUI implements Listener {\n\n'
    '    private static final String GUI_TITLE = "\u00a76\u00a7l\u7d81\u5b9a\u4efb\u52d9 \u2014 \u9078\u64c7\u76ee\u6a19\u4efb\u52d9";\n'
    '    private final NamespacedKey QUEST_ID_KEY;\n\n'
    '    private final JavaPlugin plugin;\n'
    '    private final NpcManager npcManager;\n'
    '    /** \u6b63\u5728\u958b\u555f GUI \u7684\u73a9\u5bb6 UUID \u2192 \u76ee\u6a19 NpcEntry */\n'
    '    private final Map<UUID, NpcManager.NpcEntry> pending = new HashMap<>();\n\n'
    '    public QuestBindGUI(JavaPlugin plugin, NpcManager npcManager) {\n'
    '        this.plugin     = plugin;\n'
    '        this.npcManager = npcManager;\n'
    '        this.QUEST_ID_KEY = new NamespacedKey(plugin, "bind_quest_id");\n'
    '    }\n\n'
    '    /**\n'
    '     * \u958b\u555f\u7d66\u7ba1\u7406\u54e1\u7684\u4efb\u52d9\u9078\u64c7 GUI\u3002\n'
    '     * \u5217\u51fa\u6240\u6709\u73fe\u6709 BQ \u4efb\u52d9\uff0c\u4e26\u6a19\u793a\u76ee\u524d\u5df2\u7d81\u5b9a\u7684\u4efb\u52d9\u3002\n'
    '     */\n'
    '    public void open(Player player, NpcManager.NpcEntry npc) {\n'
    '        List<Quest> quests;\n'
    '        try {\n'
    '            quests = new ArrayList<>(QuestsAPI.getAPI().getQuestsManager().getQuests());\n'
    '        } catch (Exception e) {\n'
    '            player.sendMessage("\u00a7c\u7121\u6cd5\u53d6\u5f97\u4efb\u52d9\u5217\u8868\uff1a" + e.getMessage());\n'
    '            return;\n'
    '        }\n\n'
    '        // \u7b2c\u4e00\u683c\uff1a\u53d6\u6d88\u7d81\u5b9a\uff1b\u5176\u5f8c\u4f9d\u5e8f\u5217\u51fa\u5404\u4efb\u52d9\n'
    '        int size = Math.min(54, (int) Math.ceil((quests.size() + 1) / 9.0) * 9);\n'
    '        if (size < 9) size = 9;\n'
    '        Inventory inv = Bukkit.createInventory(null, size, GUI_TITLE);\n\n'
    '        // \u53d6\u6d88\u7d81\u5b9a\u6309\u9215\n'
    '        ItemStack unbindItem = new ItemStack(Material.BARRIER);\n'
    '        ItemMeta um = unbindItem.getItemMeta();\n'
    '        if (um != null) {\n'
    '            um.setDisplayName("\u00a7c\u53d6\u6d88\u7d81\u5b9a");\n'
    '            um.setLore(Collections.singletonList("\u00a77\u9ede\u64ca\u5c07\u6b64 NPC \u8abf\u554a\u672a\u7d81\u5b9a\u72c0\u614b"));\n'
    '            um.getPersistentDataContainer().set(QUEST_ID_KEY, PersistentDataType.INTEGER, -1);\n'
    '            unbindItem.setItemMeta(um);\n'
    '        }\n'
    '        inv.setItem(0, unbindItem);\n\n'
    '        // \u5404\u4efb\u52d9\u7269\u54c1\n'
    '        int slot = 1;\n'
    '        for (Quest quest : quests) {\n'
    '            if (slot >= size) break;\n'
    '            ItemStack raw = quest.getQuestItem();\n'
    '            ItemStack qItem = (raw != null && raw.getType() != Material.AIR)\n'
    '                    ? raw.clone() : new ItemStack(Material.PAPER);\n'
    '            ItemMeta meta = qItem.getItemMeta();\n'
    '            if (meta == null) meta = Bukkit.getItemFactory().getItemMeta(qItem.getType());\n\n'
    '            meta.setDisplayName("\u00a7e" + quest.getName());\n'
    '            List<String> lore = new ArrayList<>();\n'
    '            lore.add("\u00a77\u4efb\u52d9 ID: \u00a7b" + quest.getId());\n'
    '            String desc = quest.getDescription();\n'
    '            if (desc != null && !desc.isEmpty()) {\n'
    '                lore.add("\u00a77\u63cf\u8ff0: \u00a7f" + desc);\n'
    '            }\n'
    '            if (npc.getQuestId() == quest.getId()) {\n'
    '                lore.add("");\n'
    '                lore.add("\u00a7a\u00a7l\u25c0 \u76ee\u524d\u7d81\u5b9a");\n'
    '            }\n'
    '            meta.setLore(lore);\n'
    '            meta.getPersistentDataContainer().set(QUEST_ID_KEY, PersistentDataType.INTEGER, quest.getId());\n'
    '            qItem.setItemMeta(meta);\n'
    '            inv.setItem(slot++, qItem);\n'
    '        }\n\n'
    '        pending.put(player.getUniqueId(), npc);\n'
    '        player.openInventory(inv);\n'
    '        player.sendMessage("\u00a77\u6b63\u5728\u70ba NPC \u300a\u00a7e" + npc.getName() + "\u00a77\u300b \u9078\u64c7\u7d81\u5b9a\u4efb\u52d9...");\n'
    '    }\n\n'
    '    @EventHandler\n'
    '    public void onInventoryClick(InventoryClickEvent event) {\n'
    '        if (!(event.getWhoClicked() instanceof Player player)) return;\n'
    '        if (!GUI_TITLE.equals(event.getView().getTitle())) return;\n'
    '        event.setCancelled(true);\n\n'
    '        ItemStack clicked = event.getCurrentItem();\n'
    '        if (clicked == null || clicked.getType() == Material.AIR || !clicked.hasItemMeta()) return;\n\n'
    '        Integer questId = clicked.getItemMeta().getPersistentDataContainer()\n'
    '                .get(QUEST_ID_KEY, PersistentDataType.INTEGER);\n'
    '        if (questId == null) return;\n\n'
    '        NpcManager.NpcEntry npc = pending.remove(player.getUniqueId());\n'
    '        if (npc == null) return;\n\n'
    '        player.closeInventory();\n\n'
    '        if (questId < 0) {\n'
    '            npcManager.bindQuest(npc, -1);\n'
    '            player.sendMessage("\u00a7a\u5df2\u53d6\u6d88 NPC \u300a\u00a7f" + npc.getName() + "\u00a7a\u300b \u7684\u4efb\u52d9\u7d81\u5b9a\u3002");\n'
    '        } else {\n'
    '            npcManager.bindQuest(npc, questId);\n'
    '            String questName = questId.toString();\n'
    '            try {\n'
    '                Quest q = QuestsAPI.getAPI().getQuestsManager().getQuest(questId);\n'
    '                if (q != null) questName = q.getName();\n'
    '            } catch (Exception ignored) {}\n'
    '            player.sendMessage("\u00a7a\u5df2\u5c07 NPC \u300a\u00a7f" + npc.getName()\n'
    '                    + "\u00a7a\u300b \u7d81\u5b9a\u5230\u4efb\u52d9\u300a\u00a7e" + questName + "\u00a7a\u300b (\u4efb\u52d9 ID: " + questId + ")");\n'
    '        }\n'
    '    }\n\n'
    '    @EventHandler\n'
    '    public void onInventoryClose(InventoryCloseEvent event) {\n'
    '        if (!(event.getPlayer() instanceof Player player)) return;\n'
    '        if (!GUI_TITLE.equals(event.getView().getTitle())) return;\n'
    '        pending.remove(player.getUniqueId());\n'
    '    }\n'
    '}\n'
)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Done. Size:', os.path.getsize(path))

