name: CustomRPG
version: '1.0'
main: com.customrpg.CustomRPG
api-version: '1.21'
description: A professional RPG plugin with custom weapons, skills, and mobs
author: CustomRPG Team
website: https://github.com/customrpg

commands:
  weapon:
    description: Give custom weapons to players
    usage: /weapon <weapon_name> [player] OR /weapon list OR /weapon reload
    permission: customrpg.weapon
    permission-message: You don't have permission to use this command!
    aliases: [weapons, customweapon, cweapon]
  custommob:
    description: Spawn and manage custom mobs
    usage: /custommob <spawn|list|info> [mob_key]
    permission: customrpg.mob
    permission-message: You don't have permission to use this command!
    aliases: [cmob, custommobs, spawncmob]
  rpg:
    description: Manage player stats and RPG features
    usage: /rpg <gui|stats|setstat|reload> [args]
    permission: customrpg.rpg
    permission-message: You don't have permission to use this command!
  stats:
    description: View and manage player stats
    usage: /stats [gui|player]
    permission: customrpg.rpg
    permission-message: You don't have permission to use this command!
    aliases: [playerstats]
  talent:
    description: Manage talent points and talent tree
    usage: /talent [warrior|mage|assassin|give|reset|info|reload|help]
    permission: customrpg.talent
    permission-message: You don't have permission to use this command!
    aliases: [talents, skill, skills]

permissions:
  customrpg.*:
    description: Gives access to all CustomRPG features
    children:
      customrpg.weapon: true
      customrpg.weapon.others: true
      customrpg.rpg: true
      customrpg.talent: true
      customrpg.talent.admin: true
      customrpg.admin: true
  customrpg.weapon:
    description: Allows using the /weapon command for yourself
    default: op
  customrpg.weapon.others:
    description: Allows giving weapons to other players
    default: op
  customrpg.rpg:
    description: Allows viewing own stats
    default: true
  customrpg.talent:
    description: Allows using talent system and GUI
    default: true
  customrpg.talent.admin:
    description: Allows managing other players' talents
    default: op
  customrpg.admin:
    description: Administrative access to all features
    default: op
